### PR TITLE
generator target directory can be specified through the command line

### PR DESCRIPTION
**Pull request by aaivazis**
@montemishkin: I figured a solution to building the project in the current directory was to specify the target as a command line argument. That means you can run the generator like so:

`yo nautilus:project ./relative` or `yo nautilus:project /absolute/path`

What do you think?

note: it will create the directories if they don't exist

### CODE REVIEW

**Comment by montemishkin** [comment]
does it default to cwd?

**Comment by aaivazis** [comment]
damn i just realized this is pretty hard to review since every file was changed. It has the previous default behavior of ./<project_name>.

**Comment by montemishkin** [comment]
actually, i was just looking at it and it seems pretty clear

looks like it defaults to cwd + project name. or did I interpret that incorrectly?

**Comment by aaivazis** [comment]
No you're correct. fucking github markdow... i forgot the backticks

**Comment by montemishkin** [comment]
looks good to me

:bread:

**Pull request merged**
